---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflowserver
  namespace: kubeflow
imagePullSecrets:
- name: artifactory-creds-kubeflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-server
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: mlflow-tracking-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mlflow-tracking-server
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: mlflowserver
      containers:
      - name: mlflow-tracking-server
        image: r-2i84-datamlops-docker-local.artifactory.2b82.aws.cloud.airbus.corp/arnaud/mlflow:v12
        ports:
        - containerPort: 5000
        env:
        # FILE_DIR can not be mount dir, MLFLOW need a empty dir but mount dir has lost+found
        - name: FILE_DIR
          value: /mnt/mlflow/manifest
        - name: AWS_MLFLOW_BUCKET
          value: mlflow_tmp
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: secretkey
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-server
  namespace: kubeflow
  labels:
    app: mlflow-tracking-server
spec:
  ports:
  - port: 5376
    targetPort: 5000
    protocol: TCP
  selector:
    app: mlflow-tracking-server
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mlflow-tracking-server
  namespace: kubeflow
spec:
  gateways:
    - kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /mlflow-aws/
      rewrite:
        uri: /
      route:
        - destination:
            host: mlflow-tracking-server.kubeflow.svc.cluster.local
            port:
              number: 5376
#---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: mlflow-tracking-server-viewer
#  namespace: kubeflow
#spec:
#  selector:
#    matchLabels:
#      app: mlflow-tracking-server
#  action: ALLOW
#  rules:
#  - {}
#---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: mlflow-db
#  namespace: kubeflow
#spec:
#  rules:
#  - from:
#    - source:
#        principals:
#        - cluster.local/ns/kubeflow/sa/mlflowserver
#  selector:
#    matchLabels:
#      app: mlflow-db
#---
#apiVersion: "networking.istio.io/v1alpha3"
#kind: DestinationRule
#metadata:
#  name: mlflow-mlflow-db
#  namespace: kubeflow
#spec:
#  host: mlflow-db.kubeflow.svc.cluster.local
#  trafficPolicy:
#    tls:
#      mode: ISTIO_MUTUAL
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: EnvoyFilter
#metadata:
#  name: mlflow-db
#  namespace: kubeflow
#spec:
#  configPatches:
#  - applyTo: VIRTUAL_HOST
#    match:
#      context: SIDECAR_OUTBOUND
#      routeConfiguration:
#        vhost:
#          name: mlflow-db.kubeflow.svc.cluster.local:3316
#          route:
#            name: default
#    patch:
#      operation: MERGE
#      value:
#        request_headers_to_add:
#        - append: true
#          header:
#            key: kubeflow-userid
#            value: user@example.com
#  workloadSelector:
#    labels:
#      app: mlflow-tracking-server