kubectl -n kubeflow-user-example-com delete all --all
kubectl delete -k common/istio-ingress/base
kubectl delete -k common/user-namespace/base
kubectl delete -k apps/mpi-job/upstream/overlays/kubeflow
kubectl delete -k apps/training-operator/upstream/overlays/kubeflow
kubectl delete -k apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
kubectl delete -k apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
kubectl delete -k apps/volumes-web-app/upstream/overlays/istio
kubectl delete -k apps/profiles/upstream/overlays/kubeflow
kubectl delete -k apps/jupyter/jupyter-web-app/upstream/overlays/istio
kubectl delete -k apps/jupyter/notebook-controller/upstream/overlays/kubeflow
kubectl delete -k apps/admission-webhook/upstream/overlays/cert-manager
kubectl delete -k apps/centraldashboard/upstream/overlays/istio
kubectl delete -k apps/katib/upstream/installs/katib-with-kubeflow
kubectl delete -k apps/kfserving/upstream/overlays/kubeflow
kubectl delete -k apps/pipeline/upstream/env/platform-agnostic-multi-user-pns
kubectl delete -k apps/pipeline/upstream/env/platform-agnostic-multi-user
kubectl delete -k common/istio-1-9/kubeflow-istio-resources/base
kubectl delete -k common/kubeflow-roles/base
kubectl delete -k common/kubeflow-namespace/base
kubectl delete -k common/knative/knative-eventing/base
kubectl delete -k common/istio-1-9/cluster-local-gateway/base
kubectl delete -k common/knative/knative-serving/base
kubectl delete -k common/oidc-authservice/base
kubectl delete -k common/dex/overlays/istio
kubectl delete -k common/istio-1-9/istio-install/base
kubectl delete -k common/istio-1-9/istio-namespace/base
kubectl delete -k common/istio-1-9/istio-crds/base
kubectl delete -k common/cert-manager/kubeflow-issuer/base
kubectl delete -k common/cert-manager/cert-manager/base
